services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: atmoswatch
      POSTGRES_USER: atmoswatch
      POSTGRES_PASSWORD: atmoswatch123
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://atmoswatch:atmoswatch123@postgres:5432/atmoswatch
    depends_on:
      - redis
      - postgres
